name: CI
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      go-versions: ${{ steps.versions.outputs.matrix }}
      lint-versions: ${{ steps.versions.outputs.lint_matrix }}
    steps:
      - id: versions
        run: |
          all_versions='["1.24", "1.25", "1.26"]'
          filtered=$(jq -c --argjson exclude "[]" '[.[] | select(. as $v | $exclude | index($v) | not)]' <<< "$all_versions")
          echo "matrix=$filtered" >> $GITHUB_OUTPUT
          echo "lint_matrix=[\"1.26\"]" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.setup.outputs.go-versions) }}
    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: ${{ matrix.version }}

      - name: Test
        run: make test
        env:
          GOTOOLCHAIN: local

  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: true
      matrix:
        version:
          - "stable"
          - "oldstable"
    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: ${{ matrix.version }}

      - name: Build
        run: go build ./cmd/oapi-codegen
        env:
          GOTOOLCHAIN: local
